### PR TITLE
feat: support other package managers -- add tests for pnpm

### PR DESCRIPTION
**Pull request by Cubid**
I am adding some tests on `pnpm`.   
And also a refactoring to centralise some of the commands.

But I am not sure they will run with Github Actions.

### CODE REVIEW

**Comment by ext** [comment]
Is Lerna v5 an issue? Perhaps it would be better to drop support for it instead?

**Comment by Cubid** [comment]
> Is Lerna v5 an issue? Perhaps it would be better to drop support for it instead?

It does not support `workspace:` URL type for package. I think it is just a combination, so I don't think it is really an issue.  
https://github.com/lerna/lerna/issues/2564

**Comment by Cubid** [comment]
@ext Can we merge this?

**Comment by ext** [comment]
> @ext Can we merge this?

Ah, yes sorry forgot to merge this one

**Comment by Cubid** [comment]
> > @ext Can we merge this?
> 
> Ah, yes sorry forgot to merge this one

No problem
Thanks a lot :)

**Pull request merged**
